# Generated by Django 3.0.6 on 2020-05-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fthenounproject.com%2Fterm%2Fcaptain%2F258766%2F&psig=AOvVaw20SqWNEYqM53Kl6eXA3d4m&ust=1589481493063000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCKC7jpW-sekCFQAAAAAdAAAAABAD', max_length=999),
        ),
    ]
