# Generated by Django 3.0.6 on 2020-05-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200513_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(default='https://static.thenounproject.com/png/258763-200.png', max_length=999),
        ),
    ]
