# Generated by Django 3.0.6 on 2020-05-13 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('user', '0005_auto_20200513_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
