# Generated by Django 3.0.6 on 2020-05-14 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
